### ISSUE TITLE
about the LadderBots.json file's set on "RootPath"

### ISSUE THREAD

**Issue by DKuan** [Archiatrus/pysc2-ladderbot#1]
the ladder_manager has no "RootPath",and the name is Path.Also, the "filename" is not existing.When I change the "RootPath" to "Path",it's right and it work fine.But I can't see the picture always when the game start, did you have this problem ?

**Comment by Archiatrus** [comment]
Unfortunately, [this](https://github.com/Cryptyc/Sc2LadderServer/pull/25) PR was not yet merged with the LadderManager. Try my fork or wait (hopefully) till this evening or tomorrow evening.

**Comment by Archiatrus** [comment]
The pull request was merged. Now the LadderBots.json file has the fields RootPath and FileName: [see here](https://github.com/Cryptyc/Sc2LadderServer/blob/master/LadderBots.json#L6)
